version: 0.1.{build}

image: Visual Studio 2019

environment:
  CF-USERNAME:
    secure: oriv4yD52p7YMGJ4HKXA4Q==
  CF-API-KEY:
    secure: 3wXhsrd3N9qouW0jRNW2oUnrErPC/lwUD4nbe400JncUBLhOObr+A8LTKjM8I0Nl
    
configuration: Release

build_script:
- cmd: dotnet publish -c Release BlazorApp2/BlazorApp2.csproj

artifacts:
- path: '\BlazorApp2\bin\Release\netcoreapp3.1\publish'
  name: blazorapp2
  type: zip
  
deploy:
- provider: AzureAppServiceZipDeploy
  website: blazorapp2-ui
  username: $blazorapp2-ui
  password:
    secure: oWYfA4Jz7mrl1+5uVcnre3Gw781WumfE5qbNZ86RZZslV9RFD5oWrwrjBvsb6YAbx1VCxEbZF80UnvREHA4ZZA==
  async_deploy: false
  
  on:
    branch: master
